name: C/C++ CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Install glm
      run: wget https://github.com/g-truc/glm/archive/0.9.8.3.tar.gz && tar -xzvf 0.9.8.3.tar.gz && cd glm-0.9.8.3 && cmake . && make && sudo make install && cd ..
    - name: Update package lists
      run: sudo apt-get update
    - name: Install dependencies
      run: sudo apt-get install -y libopencv-dev libtiff-dev
    - name: config
      run: mkdir build && cd build && cmake .. -DGTEST=ON -DENABLE_CUDA=OFF -DTEST_DATA_PATH="../../data/" -DTEST_REF_PATH="../../test/data/"
    - name: build
      working-directory: build
      run: make
    - name: test
      working-directory: build
      run: ctest --rerun-failed --output-on-failure
      continue-on-error: true
